[package]
name = "gemini-video-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gemini-engine = { version = "0.14.1", default-features = false }
image = "0.24.7"
